id: A47AB5BBD
title: 'The Song of Devotion: Verses of Aspiration for the Fulfilment of the Enlightened
  Vision of Khenchen Jigme Phuntsok, the Reincarnation of Terton Lerab Lingpa'
type: translation
pechas:
- IDC6EFA15
- IF9DDE364
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:43.057984
  last_modified_at: 2023-01-04 11:52:43.057995
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  IDC6EFA15/30AE: B767
  IF9DDE364/2D2E: B767
